title:              Coffee Notes
email:              kzabelova@gmail.com
description:        Notes and sketches in computer scinces
author:             Kate from IT
# baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://tobichimaru.github.io/coffee-notes/"
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

# Social Profiles
github_username:    tobichimaru
instagram_username:  kateonduty
linkedin_username: kate-zabelova

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
